name: Lint
on:
  - push
  - pull_request
jobs:
  lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run GolangCI-Lint
        uses: ./
